In [3]:
import pandas as pd

In [4]:
Train_data =pd.read_csv("C:\\Users\\prati\\Downloads\\Loan_Prediction_Dataset_25000.csv")
Train_data.head()

,id,applicant_income,coapplicant_income,total_income,loan_amount,loan_term,monthly_loan_payment,credit_score,employment_years,age,...,property_area,property_value,credit_history,previous_loans,loan_defaults,bankruptcy_history,monthly_expenses,debt_ratio,loan_to_income_ratio,risk_flag
0,1,43654,37522,81176,518870,180,2882.61,623,8,46,...,Semiurban,116502,1,1,0,0,1900,0.21,6.39,0
1,2,43654,37522,81176,215850,300,719.50,623,11,46,...,Rural,502401,1,1,0,0,3994,0.09,2.66,0
2,3,43654,37522,81176,215850,240,899.38,623,8,23,...,Rural,880796,1,1,0,0,7768,0.09,2.66,0
3,4,75860,0,75860,215850,180,1199.17,687,0,33,...,Urban,135807,1,3,0,0,6621,0.09,2.85,0
4,5,60795,0,60795,56572,180,314.29,687,11,56,...,Rural,508311,1,2,0,0,7104,0.05,0.93,0

In [5]:
Train_data.describe()

,id,applicant_income,coapplicant_income,total_income,loan_amount,loan_term,monthly_loan_payment,credit_score,employment_years,age,dependents,property_value,credit_history,previous_loans,loan_defaults,bankruptcy_history,monthly_expenses,debt_ratio,loan_to_income_ratio,risk_flag
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000
mean,12500.500000,64784.863200,23914.648480,88699.511680,208319.558920,269.635200,869.395858,671.568280,5.501160,37.422120,1.387360,549956.111840,0.847760,1.569320,0.179400,0.047160,4500.386840,0.098230,2.721846,0.07112
std,7217.022701,32777.663766,19738.012249,38259.063522,122005.875242,79.652198,648.538991,73.916224,3.646298,11.405876,1.196867,260543.931193,0.359261,1.345239,0.456272,0.211985,2018.944284,0.059012,1.987028,0.25703
min,1.000000,43654.000000,0.000000,43654.000000,56572.000000,120.000000,157.140000,568.000000,0.000000,23.000000,0.000000,100045.000000,0.000000,0.000000,0.000000,0.000000,1000.000000,0.050000,0.230000,0.00000
25%,6250.750000,43654.000000,0.000000,60795.000000,56572.000000,180.000000,314.290000,623.000000,4.000000,33.000000,0.000000,324078.500000,1.000000,0.000000,0.000000,0.000000,2757.000000,0.050000,0.930000,0.00000
50%,12500.500000,60795.000000,37522.000000,81176.000000,215850.000000,300.000000,719.500000,687.000000,4.000000,33.000000,1.000000,549466.500000,1.000000,1.000000,0.000000,0.000000,4500.500000,0.080000,2.390000,0.00000
75%,18750.250000,75860.000000,37522.000000,98317.000000,339001.000000,360.000000,1199.170000,687.000000,8.000000,46.000000,2.000000,777581.750000,1.000000,2.000000,0.000000,0.000000,6234.000000,0.120000,3.550000,0.00000
max,25000.000000,196820.000000,46680.000000,243500.000000,518870.000000,360.000000,4323.920000,795.000000,11.000000,56.000000,4.000000,999997.000000,1.000000,5.000000,2.000000,1.000000,7999.000000,0.400000,11.890000,1.00000

In [6]:
Train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    25000 non-null  int64
 1   applicant_income      25000 non-null  int64
 2   coapplicant_income    25000 non-null  int64
 3   total_income          25000 non-null  int64
 4   loan_amount           25000 non-null  int64
 5   loan_term             25000 non-null  int64
 6   monthly_loan_payment  25000 non-null  float64
 7   credit_score          25000 non-null  int64
 8   employment_years      25000 non-null  int64
 9   age                   25000 non-null  int64
 10  dependents            25000 non-null  int64
 11  gender                25000 non-null  object
 12  marital_status        25000 non-null  object
 13  education             25000 non-null  object
 14  employment_status     25000 non-null  object
 15  property_area         25000 non-null  object
 16  property_value        25000 non-null  int64
 17  credit_history        25000 non-null  int64
 18  previous_loans        25000 non-null  int64
 19  loan_defaults         25000 non-null  int64
 20  bankruptcy_history    25000 non-null  int64
 21  monthly_expenses      25000 non-null  int64
 22  debt_ratio            25000 non-null  float64
 23  loan_to_income_ratio  25000 non-null  float64
 24  risk_flag             25000 non-null  int64
dtypes: float64(3), int64(17), object(5)
memory usage: 4.8+ MB

In [7]:
Train_data.isna().sum()

id                      0
applicant_income        0
coapplicant_income      0
total_income            0
loan_amount             0
loan_term               0
monthly_loan_payment    0
credit_score            0
employment_years        0
age                     0
dependents              0
gender                  0
marital_status          0
education               0
employment_status       0
property_area           0
property_value          0
credit_history          0
previous_loans          0
loan_defaults           0
bankruptcy_history      0
monthly_expenses        0
debt_ratio              0
loan_to_income_ratio    0
risk_flag               0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
lr =LabelEncoder()
Train_data["marital_status"] = lr.fit_transform(Train_data["marital_status"])
Train_data["employment_status"] = lr.fit_transform(Train_data["employment_status"])
Train_data["property_area"] = lr.fit_transform(Train_data["property_area"])
Train_data["education"] = lr.fit_transform(Train_data["education"])
Train_data["gender"] = lr.fit_transform(Train_data["gender"])

In [9]:
Train_data[["gender", "marital_status", "education","employment_status", "property_area"]]

       gender  marital_status  education  employment_status  property_area
0           0               2          2                  1              1
1           1               1          2                  0              0
2           0               1          0                  0              0
3           0               1          0                  0              2
4           0               1          1                  1              0
...       ...             ...        ...                ...            ...
24995       1               1          0                  1              1
24996       1               1          0                  0              1
24997       0               2          0                  0              2
24998       1               1          1                  0              1
24999       1               2          1                  0              2

[25000 rows x 5 columns]

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report


X = Train_data[["credit_score", "credit_history", "applicant_income",
        "coapplicant_income", "loan_amount", "loan_term",
        "employment_years", "age", "dependents", "previous_loans",
        "monthly_expenses", "property_value",
        "gender", "marital_status", "education",
        "employment_status", "property_area"]]

Y = Train_data["risk_flag"]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(f"Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(classification_report(y_test, y_pred))

Accuracy: 94.72%
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      6924
           1       0.76      0.45      0.57       576

    accuracy                           0.95      7500
   macro avg       0.86      0.72      0.77      7500
weighted avg       0.94      0.95      0.94      7500

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report
rf_model =RandomForestClassifier(
    n_estimators=100,
    max_depth=100,
    random_state=42,
)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)
print(y_pred)

acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc * 100:.2f}%")

[0 0 0 ... 0 0 0]
Accuracy: 95.77%

In [21]:
from sklearn.ensemble import GradientBoostingClassifier
gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42,
)
gb_model.fit(X_train, y_train)
y_pred = gb_model.predict(X_test)
print(y_pred)
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy: {acc * 100:.2f}%")

[0 0 0 ... 0 0 0]
Accuracy: 95.65%

In [19]:
import pickle
# created pickle file to Save trained model
with open("model.pkl","wb") as f:
     pickle.dump(model,f)

with open("scaler.pkl","wb") as f:
     pickle.dump(scaler,f)